name:                kafkerr
version:             0.1.0.0
license:             BSD3
author:              "@marcinb"
maintainer:          "marcin.baraniecki@softwaremill.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/kafkerr#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- hw-kafka-client

library:
  source-dirs: src

executables:
  kafkerr-consumer:
    main:                Main.hs
    source-dirs:         app/consumer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kafkerr
  kafkerr-producer:
    main:                Main.hs
    source-dirs:         app/producer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kafkerr  

tests:
  kafkerr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kafkerr
